#!/usr/bin/python
# coding=UTF-8

# Model specification validation and processing:
# 1. Load model
# 2. Validate model for self-consistency and correctness
# 3. Convert model to documentation
# 4. Convert model to reference implementation

import sys
import os

sys.path.insert(0, os.path.abspath('python'))

import model
import sphinx

if __name__ == "__main__":
    model = model.Model()
    sphinx = sphinx.Sphinx(model)

    sphinx.dump_primitivelist()
    sphinx.dump_enums()
    sphinx.dump_compounds()
    sphinx.dump_shapelist()
    sphinx.dump_replist()
    sphinx.dump_shapereps()
    sphinx.dump_repmembers()
    sphinx.dump_relgraph()

    model.dump_java()
    model.dump_cxx()
