#!/usr/bin/python
# coding=UTF-8

# Model specification validation and processing:
# 1. Load model
# 2. Validate model for self-consistency and correctness
# 3. Convert model to documentation
# 4. Convert model to reference implementation

import sys
import os

sys.path.insert(0, os.path.abspath('python'))

import model
import sphinx
import cxx
import java

if __name__ == "__main__":
    model = model.Model()
    sphinx = sphinx.Sphinx(model)
    java = java.Java(model)

    sphinx.dump()
#    cxx.dump()
    java.dump()
