#!/usr/bin/python
# coding=UTF-8

# Model specification validation and processing:
# 1. Load model
# 2. Validate model for self-consistency and correctness
# 3. Convert model to documentation
# 4. Convert model to reference implementation

import sys
import os

sys.path.insert(0, os.path.abspath('python'))

import model

if __name__ == "__main__":
    model = model.Model()

    model.dump_primitivelist()
    model.dump_enums()
    model.dump_compounds()
    model.dump_shapelist()
    model.dump_replist()
    model.dump_shapereps()
    model.dump_repmembers()
    model.dump_relgraph()
    model.dump_java()
    model.dump_cxx()
