#!/bin/sh

set -e

PRIMITIVES="primitives.txt"
COMPOUND="compound.txt"
SHAPES="shapes.txt"
SHAPEREPS="shapereps.txt"
REPS="representations.txt"
REPSMEMBERS="representationmembers.txt"

listprimitives() {
    cut -f1 "$PRIMITIVES" | grep -v '^Primitive$' | sort | uniq
}

listcompounds() {
    cut -f1 "$COMPOUND" | grep -v '^Primitive' | sort | uniq
}

listshapes() {
       cut -f2 "$SHAPES" | grep -v '^Shape' | sort | uniq
}

listreps() {
       cut -f2 "$REPS" | grep -v '^Representation' | sort | uniq
}

shaperows() {
    egrep "^(Shape|$1)	" "$SHAPEREPS"
}

listshapereps() {
       shaperows "$1" | cut -f 2 | grep -v '^RepIn' | sort | uniq
}

dumprep () {
    egrep  "^Representation	" "$REPSMEMBERS" | cut -f 2,3,4,5
    egrep  "^$1	" "$REPSMEMBERS" | cut -f 2,3,4,5 | sort -n -k 1
}

dumpreptables() {
    [ ! -d gen ] && mkdir gen
    REPRST="gen/representations.rst"
    rm -f "$REPRST"

    for rep in $(listreps); do
        REPTAB="gen/rep-$rep.gen.txt"
	echo "Dumping $REPTAB"
	dumprep "$rep"  > "$REPTAB"

	echo <<EOF >> "$REPRST"
$rep
-------------------------------------------------

.. csv-table:: $rep
    :header-rows: 1
    :file: $REPTAB
    :delim: tab


EOF
    done
}

gencxxtypes() {
:
}

CMD=$1
shift

case "$CMD" in
    listprimitives)
	listprimitives;;
    listcompounds)
	listcompounds;;
    listshapes)
	listshapes;;
    listreps)
	listreps;;
    listshapereps)
	listshapereps "$1";;
    dumprep)
	dumprep "$1";;
    dumpreptables)
	dumpreptables;;
    dumptables)
	dumptables;;
    cxx)
        gencxxtypes;;
    *)
	echo "Unknown command"
	exit 1
	;;
esac
